# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1.13'
gem 'dotenv'
gem 'puma', '~> 6.6'
gem 'rackup', '~> 2.2'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sqlite3'
gem 'httparty'
gem 'nokogiri'
gem 'rubocop', '~> 1.72', require: false

group :test do
    gem 'minitest'
    gem 'rack-test'
  end
